name: Bug Report
description: File a bug report
title: "Bug: "
labels: ["bug"]
body:
  - type: checkboxes
    id: checklist
    attributes:
      label: Make sure you have done the following
      options:
        - label: I have updated to the latest version of the plugin.
          required: true
        - label: I have read the README.
          required: true
        - label: >
            All Treesitter parsers for the filetypes used by nvim-puppeteer are installed,  and I updated
            all my Treesitter parsers via `:TSUpdate`.
          required: true
  - type: textarea
    id: bug-description
    attributes:
      label: Bug Description
      description: A clear and concise description of the bug.
    validations: { required: true }
  - type: textarea
    id: screenshot
    attributes:
      label: Relevant Screenshot
      description: If applicable, add screenshots or a screen recording to help explain your problem.
  - type: textarea
    id: reproduction-steps
    attributes:
      label: To Reproduce
      description: Please include example code where the plugin is not working.
      placeholder: |
        For example:
        1. In the filetype…
        2. Given a string like this … with the cursor positioned at…
    validations: { required: true }
  - type: textarea
    id: version-info
    attributes:
      label: neovim version
      render: Text
    validations: { required: true }
